name: "ecom-cms-test"

volumes:
  db-data:

services:
  remix:
    build:
      context: ./docker/node
      args:
        - UID=${UID}
        - GID=${GID}
        - USER_NAME=${USER_NAME}
    user: ${UID}:${GID}
    volumes:
      - ./source:/app
    ports:
      - 3000:3000
    command:
      - npm
      - run
      - dev

  db:
    container_name: postgres_container
    image: postgres
    restart: always
    shm_size: 1024mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "3080:80"
